config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: %i[ show edit update destroy ]

  # GET /notifications or /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1 or /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications or /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to notification_url(@notification), notice: "Notification was successfully created." }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1 or /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to notification_url(@notification), notice: "Notification was successfully updated." }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1 or /notifications/1.json
  def destroy
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url, notice: "Notification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:text, :shown)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodosClient</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notifications/_form.html.erb
<%= form_with(model: notification) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
        <% notification.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :shown %>
    <%= form.check_box :shown %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Shown</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.text %></td>
        <td><%= notification.shown %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @notification.text %>
</p>

<p>
  <strong>Shown:</strong>
  <%= @notification.shown %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>